### ISSUE TITLE
crash game when I remove the upgraded sword

### ISSUE THREAD

**Issue by prufme** [Wehavecookies56/Bonfires#46]
Mod version: 1.2.15
Minecraft version: 1.18.2
Forge version: 40.2.18

hi, the game just crashes when I remove the upgraded sword

-- Head --
Thread: Render thread
Suspected Mod: 
	Bonfires (bonfires), Version: 1.18.2-1.2.15-a007ac4
		at TRANSFORMER/bonfires@1.18.2-1.2.15-a007ac4/wehavecookies56.bonfires.setup.ClientSetup.tooltipEvent(ClientSetup.java:53)
Stacktrace:
	at wehavecookies56.bonfires.setup.ClientSetup.tooltipEvent(ClientSetup.java:53) ~[Bonfires-1.18.2-1.2.15-a007ac4.jar%2383!/:1.18.2-1.2.15-a007ac4] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.eventbus.ASMEventHandler_2239_ClientSetup_tooltipEvent_ItemTooltipEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:275) ~[forge-1.18.2-40.2.18-universal.jar%23261!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:768) ~[client-1.18.2-20220404.173914-srg.jar%23256!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,pl:rei_plugin_compatibilities:B,xf:fml:forge:itemstack,pl:mixin:APP:unbreakable.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:APP:extendedgears-common.mixins.json:MixinItemStack,pl:mixin:APP:justleveling.mixins.json:MixItemStack,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.client.gui.screens.Screen.m_96555_(Screen.java:194) ~[client-1.18.2-20220404.173914-srg.jar%23256!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:configured:set_background_texture_2,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:kiwi.mixins.json:ScreenMixin,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:customnpcs.mixins.json:ScreenMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_6057_(Screen.java:171) ~[client-1.18.2-20220404.173914-srg.jar%23256!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:configured:set_background_texture_2,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:kiwi.mixins.json:ScreenMixin,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:customnpcs.mixins.json:ScreenMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6057_(CreativeModeInventoryScreen.java:671) ~[client-1.18.2-20220404.173914-srg.jar%23256!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7025_(AbstractContainerScreen.java:173) ~[client-1.18.2-20220404.173914-srg.jar%23256!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:636) ~[client-1.18.2-20220404.173914-srg.jar%23256!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.2.18-universal.jar%23261!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.2.18-universal.jar%23261!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}

**Comment by Wehavecookies56** [comment]
Remove from where? Not entirely sure what you mean

**Comment by prufme** [comment]
> Remove from where? Not entirely sure what you mean

i get it that's not the problem. when I hold left shift on a upgraded weapon in inventory, the game crashes

**Comment by Wehavecookies56** [comment]
This should now be fixed in 1.2.18
