### ISSUE TITLE
Game Crash When Accessing Bonfire

### ISSUE THREAD

**Issue by CrimsonNecrosis** [Wehavecookies56/Bonfires#5]
Anytime I access a bonfire, the game hard crashes. It was working fine until I saved the server then reloaded it. No new mods were added between server loads. It even crashes during single player.

Here is the crash log!

craft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/10/17 1:33 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: toIndex = 7
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at uk.co.wehavecookies56.bonfires.gui.GuiBonfire.createSeries(GuiBonfire.java:84)
	at uk.co.wehavecookies56.bonfires.gui.GuiBonfire.updateBonfires(GuiBonfire.java:451)
	at uk.co.wehavecookies56.bonfires.gui.GuiBonfire.func_73866_w_(GuiBonfire.java:417)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:487)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:532)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:320)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:113)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2503)
	at uk.co.wehavecookies56.bonfires.blocks.BlockAshBonePile.func_180639_a(BlockAshBonePile.java:123)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:408)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at uk.co.wehavecookies56.bonfires.gui.GuiBonfire.createSeries(GuiBonfire.java:84)
	at uk.co.wehavecookies56.bonfires.gui.GuiBonfire.updateBonfires(GuiBonfire.java:451)
	at uk.co.wehavecookies56.bonfires.gui.GuiBonfire.func_73866_w_(GuiBonfire.java:417)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:487)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:532)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:320)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:113)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2503)
	at uk.co.wehavecookies56.bonfires.blocks.BlockAshBonePile.func_180639_a(BlockAshBonePile.java:123)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:408)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CrimsonNecrosis'/205, l='MpServer', x=-567.34, y=183.00, z=994.47]]
	Chunk stats: MultiplayerChunkCache: 3340, 3340
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (174,236,-414), Chunk: (at 14,14,2 in 10,-26; contains blocks 160,0,-416 to 175,255,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1257995 game time, 415301 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 117 total; [EntityCreeper['Creeper'/512, l='MpServer', x=-508.50, y=166.00, z=984.50], EntitySpider['Spider'/513, l='MpServer', x=-505.50, y=166.00, z=982.50], EntityCreeper['Creeper'/514, l='MpServer', x=-501.74, y=171.00, z=990.09], EntityCreeper['Creeper'/515, l='MpServer', x=-498.50, y=171.00, z=988.50], EntityCreeper['Creeper'/516, l='MpServer', x=-502.50, y=171.00, z=987.50], EntityCreeper['Creeper'/517, l='MpServer', x=-499.50, y=165.00, z=978.50], EntityCow['Cow'/261, l='MpServer', x=-540.21, y=65.00, z=919.15], EntitySpider['Spider'/518, l='MpServer', x=-501.50, y=171.00, z=988.50], EntitySkeleton['Skeleton'/519, l='MpServer', x=-498.50, y=171.00, z=983.50], EntityItem['item.tile.gravel'/283, l='MpServer', x=-611.40, y=18.00, z=989.46], EntityFallingBlock['Falling Block'/298, l='MpServer', x=-616.50, y=29.91, z=972.50], EntityCow['Cow'/299, l='MpServer', x=-623.50, y=75.00, z=973.50], EntityCow['Cow'/304, l='MpServer', x=-627.54, y=76.00, z=978.81], EntityBat['Bat'/3383, l='MpServer', x=-553.50, y=23.10, z=1032.50], EntityBat['Bat'/3390, l='MpServer', x=-523.50, y=23.10, z=1016.50], EntityCreeper['Creeper'/319, l='MpServer', x=-549.50, y=152.00, z=1008.50], EntityBat['Bat'/3391, l='MpServer', x=-523.50, y=23.10, z=1018.50], EntitySkeleton['Skeleton'/320, l='MpServer', x=-544.50, y=154.00, z=1013.50], EntityZombie['Zombie'/321, l='MpServer', x=-552.50, y=159.00, z=1017.50], EntityCreeper['Creeper'/322, l='MpServer', x=-522.50, y=157.00, z=976.50], EntityWitch['Witch'/323, l='MpServer', x=-538.50, y=147.00, z=997.50], EntityZombie['Zombie'/324, l='MpServer', x=-543.50, y=151.00, z=998.50], EntityCreeper['Creeper'/325, l='MpServer', x=-540.50, y=175.00, z=1003.50], EntityCreeper['Creeper'/326, l='MpServer', x=-536.50, y=184.00, z=993.50], EntityItem['item.tile.gravel'/2374, l='MpServer', x=-590.50, y=20.00, z=1033.50], EntityZombie['Zombie'/327, l='MpServer', x=-543.50, y=177.00, z=999.50], EntityChicken['Chicken'/328, l='MpServer', x=-509.22, y=72.00, z=967.51], EntityChicken['Chicken'/329, l='MpServer', x=-502.58, y=75.00, z=970.87], EntityCow['Cow'/1097, l='MpServer', x=-645.63, y=76.00, z=981.39], EntityChicken['Chicken'/330, l='MpServer', x=-507.20, y=72.00, z=970.50], EntityCow['Cow'/1098, l='MpServer', x=-645.50, y=73.31, z=984.55], EntityChicken['Chicken'/331, l='MpServer', x=-505.51, y=72.00, z=968.07], EntityZombie['Zombie'/332, l='MpServer', x=-504.50, y=194.00, z=970.50], EntityCow['Cow'/1101, l='MpServer', x=-626.98, y=74.00, z=968.40], EntityCow['Cow'/1102, l='MpServer', x=-628.50, y=75.00, z=973.50], EntityCow['Cow'/335, l='MpServer', x=-606.50, y=76.00, z=1072.50], EntityFallingBlock['Falling Block'/345, l='MpServer', x=-586.50, y=20.92, z=1037.50], EntityFallingBlock['Falling Block'/348, l='MpServer', x=-585.50, y=19.92, z=1032.50], EntityItem['item.item.string'/350, l='MpServer', x=-584.88, y=19.00, z=1037.82], EntitySpider['Spider'/355, l='MpServer', x=-539.50, y=149.00, z=982.50], EntitySkeleton['Skeleton'/356, l='MpServer', x=-531.89, y=147.00, z=979.74], EntitySpider['Spider'/357, l='MpServer', x=-534.50, y=172.00, z=987.50], EntitySkeleton['Skeleton'/358, l='MpServer', x=-541.50, y=165.00, z=989.50], EntityBat['Bat'/3430, l='MpServer', x=-513.50, y=24.10, z=991.50], EntityCreeper['Creeper'/359, l='MpServer', x=-544.74, y=150.00, z=1005.77], EntityCreeper['Creeper'/360, l='MpServer', x=-547.50, y=151.00, z=1006.50], EntityCreeper['Creeper'/361, l='MpServer', x=-544.50, y=151.00, z=997.54], EntityZombie['Zombie'/362, l='MpServer', x=-544.50, y=151.00, z=999.86], EntityCreeper['Creeper'/363, l='MpServer', x=-544.50, y=151.00, z=998.26], EntityZombie['Zombie'/364, l='MpServer', x=-544.50, y=151.00, z=999.00], EntityZombie['Zombie'/365, l='MpServer', x=-544.50, y=151.00, z=996.86], EntitySkeleton['Skeleton'/366, l='MpServer', x=-548.50, y=161.00, z=994.50], EntitySkeleton['Skeleton'/367, l='MpServer', x=-516.50, y=222.00, z=968.50], EntityZombie['Zombie'/368, l='MpServer', x=-512.50, y=222.00, z=972.50], EntityItem['item.tile.gravel'/394, l='MpServer', x=-591.88, y=21.88, z=1011.72], EntityItem['item.tile.gravel'/411, l='MpServer', x=-586.75, y=20.00, z=1005.08], EntityCow['Cow'/412, l='MpServer', x=-604.80, y=74.00, z=1018.33], EntityCow['Cow'/1184, l='MpServer', x=-622.50, y=66.00, z=915.50], EntityCow['Cow'/1185, l='MpServer', x=-623.50, y=66.00, z=917.50], EntityCow['Cow'/939, l='MpServer', x=-647.32, y=64.00, z=916.60], EntityCow['Cow'/940, l='MpServer', x=-644.79, y=64.00, z=920.35], EntitySkeleton['Skeleton'/445, l='MpServer', x=-523.50, y=157.00, z=1035.50], EntityCreeper['Creeper'/446, l='MpServer', x=-515.50, y=159.00, z=1038.50], EntityCow['Cow'/1221, l='MpServer', x=-626.50, y=65.00, z=914.50], EntityCow['Cow'/1222, l='MpServer', x=-631.41, y=64.42, z=917.55], EntitySpider['Spider'/454, l='MpServer', x=-489.12, y=171.00, z=993.74], EntityCreeper['Creeper'/455, l='MpServer', x=-494.50, y=171.00, z=999.50], EntityItem['item.tile.gravel'/2250, l='MpServer', x=-622.52, y=28.92, z=969.49], EntityItem['item.tile.gravel'/2251, l='MpServer', x=-623.50, y=29.92, z=973.52], EntityPlayerSP['CrimsonNecrosis'/205, l='MpServer', x=-567.34, y=183.00, z=994.47], EntityCow['Cow'/214, l='MpServer', x=-611.55, y=77.00, z=1011.50], EntityCow['Cow'/215, l='MpServer', x=-610.51, y=75.00, z=1013.60], EntityCow['Cow'/216, l='MpServer', x=-613.50, y=76.00, z=1010.50], EntityFallingBlock['Falling Block'/217, l='MpServer', x=-606.50, y=19.88, z=993.50], EntityItem['item.item.string'/218, l='MpServer', x=-607.09, y=20.00, z=994.06], EntityItem['item.item.string'/219, l='MpServer', x=-606.13, y=18.00, z=994.13], EntityItem['item.tile.gravel'/2267, l='MpServer', x=-603.48, y=19.93, z=989.51], EntityItem['item.tile.gravel'/2268, l='MpServer', x=-588.51, y=18.93, z=1033.50], EntityZombie['Zombie'/477, l='MpServer', x=-537.02, y=153.00, z=1024.56], EntityItem['item.tile.gravel'/2269, l='MpServer', x=-590.48, y=19.93, z=1033.51], EntityZombie['Zombie'/478, l='MpServer', x=-537.64, y=153.00, z=1025.16], EntityItem['item.tile.gravel'/2270, l='MpServer', x=-555.48, y=18.93, z=1051.52], EntityZombie['Zombie'/479, l='MpServer', x=-534.50, y=164.00, z=1038.50], EntityItem['item.tile.gravel'/2271, l='MpServer', x=-554.48, y=17.93, z=1044.52], EntityFallingBlock['Falling Block'/481, l='MpServer', x=-557.50, y=19.92, z=1045.50], EntityPig['Pig'/226, l='MpServer', x=-528.50, y=67.00, z=930.50], EntityPig['Pig'/227, l='MpServer', x=-530.10, y=67.00, z=928.65], EntitySpider['Spider'/484, l='MpServer', x=-499.50, y=171.00, z=997.50], EntityPig['Pig'/228, l='MpServer', x=-530.89, y=67.00, z=927.59], EntitySkeleton['Skeleton'/485, l='MpServer', x=-502.50, y=163.00, z=994.50], EntityPig['Pig'/229, l='MpServer', x=-528.50, y=67.00, z=931.50], EntityZombie['Zombie'/486, l='MpServer', x=-526.50, y=235.00, z=1018.50], EntitySkeleton['Skeleton'/488, l='MpServer', x=-495.22, y=171.00, z=986.62], EntityZombie['Zombie'/489, l='MpServer', x=-491.50, y=171.00, z=980.50], EntityZombie['Zombie'/490, l='MpServer', x=-489.50, y=171.00, z=983.50], EntityZombie['Zombie'/491, l='MpServer', x=-490.50, y=171.00, z=979.50], EntitySkeleton['Skeleton'/493, l='MpServer', x=-488.50, y=171.00, z=991.50], EntitySkeleton['Skeleton'/494, l='MpServer', x=-488.50, y=171.00, z=991.50], EntitySpider['Spider'/495, l='MpServer', x=-493.50, y=171.00, z=985.50], EntitySkeleton['Skeleton'/496, l='MpServer', x=-495.50, y=171.00, z=985.50], EntitySkeleton['Skeleton'/497, l='MpServer', x=-487.50, y=183.00, z=991.50], EntityFallingBlock['Falling Block'/243, l='MpServer', x=-604.50, y=18.92, z=989.50], EntityItem['item.item.string'/245, l='MpServer', x=-612.20, y=19.00, z=993.92], EntityItem['item.item.string'/246, l='MpServer', x=-611.88, y=18.00, z=992.13], EntityItem['item.item.string'/502, l='MpServer', x=-562.13, y=19.00, z=1046.13], EntityItem['item.item.string'/247, l='MpServer', x=-608.88, y=18.00, z=996.62], EntitySpider['Spider'/504, l='MpServer', x=-540.50, y=155.00, z=1019.50], EntityItem['item.item.string'/248, l='MpServer', x=-608.88, y=18.00, z=994.88], EntitySpider['Spider'/505, l='MpServer', x=-540.50, y=155.00, z=1019.50], EntityItem['item.item.string'/249, l='MpServer', x=-608.98, y=19.44, z=994.08], EntityZombie['Zombie'/506, l='MpServer', x=-540.50, y=154.00, z=1013.50], EntitySkeleton['Skeleton'/507, l='MpServer', x=-539.50, y=178.00, z=1010.50], EntityCreeper['Creeper'/508, l='MpServer', x=-531.50, y=235.00, z=1023.50], EntityCreeper['Creeper'/509, l='MpServer', x=-490.50, y=185.00, z=969.50], EntitySkeleton['Skeleton'/510, l='MpServer', x=-503.83, y=150.00, z=979.80], EntityCreeper['Creeper'/511, l='MpServer', x=-504.50, y=166.00, z=984.50], EntityCow['Cow'/255, l='MpServer', x=-530.44, y=66.00, z=916.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 671114720 bytes (640 MB) / 1977360384 bytes (1885 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2262 Optifine OptiFine_1.11.2_HD_U_B7 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2262.jar) 
	UCHIJAAAA	forge{13.20.0.2262} [Minecraft Forge] (forge-1.11.2-13.20.0.2262.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	newthings{1.1-1.11.2} [101 New Things] (101 New Things 1.3-1.11.2.jar) 
	UCHIJAAAA	ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.1-8.jar) 
	UCHIJAAAA	biomesoplenty{6.1.0.2211} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2211-universal.jar) 
	UCHIJAAAA	bonfires{1.0.1} [Bonfires] (Bonfires-1.11-1.0.1.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	creeperconfetti{1.3} [Creeper Confetti] (creeperconfetti-1.3.jar) 
	UCHIJAAAA	ism{1.5.13 MC-1.1.11.2} [Instant Structures Mod (ISM)] (ism-1.5.13 MC-1.11.2.jar) 
	UCHIJAAAA	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJAAAA	levels{b1.1.1} [Levels] (Levels 2-1.11.2-b1.1.1.jar) 
	UCHIJAAAA	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCHIJAAAA	chef{5.1} [Master Chef] (Master_Chef_v5.1-1.11.jar) 
	UCHIJAAAA	moretoolsmod{1.0.0} [More Tools Mod] (mtm1.11.2 OF.jar) 
	UCHIJAAAA	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJAAAA	roguelike{1.6.5} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.5.jar) 
	UCHIJAAAA	wearablebackpacks{2.3.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.0.jar) 
	UCHIJAAAA	xaerominimap{1.12.7} [Xaero's Minimap] (Xaeros_Minimap_1.12.7_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2262
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 8
	Antialiasing: 0
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Fenrirthviti** [comment]
I am also experiencing this crash. I assume this mod is pretty much dead and no longer under active development?

**Comment by Glease** [comment]
Our server recently stumbed on the same problem. However, after me, the technical support, fixed the list index issue, found out that the GuiBonfire is actually way beyond what could be called quality and bug free code. It refuses to show second page. If you add 8 bonfire, the 7th disappears from the list. If 9, 9th and 7th disappear. If 10, still only 8th showing up. A random look at BonfireRegistry revealed the developer actually have no idea what java 8 is. I have asked the owner to reconsider adding this mod. 

I now doubt this is a half complete project of a hackathon.

**Comment by Wehavecookies56** [comment]
Sorry I haven't had time to work on the mod since I recently started university and also got a weekend job.
I'm open to suggestions for improving it and PRs.

I'm aware there are issues although I cannot seem to recreate most of them. For example the issue you mention, when I create 8 bonfires the second page shows with no issues.
Also I'm not sure what you're trying to say on that last sentence.

And thank you for your kind words.

**Comment by llk89** [comment]
Well I must say sorry in advance, yesterday we were in a rush from beta to public but this bonfire crashing and then disappearing really annoyed us so I may have been a bit too rude. 

So first off, I will skip the disappearing issue. I'm not on my develop machine and can't show you how this bug is occuring. I'll just talk about something I've found within GuiBonfire. First it is crashing whenever there are 7n-1 bonfires in a dimension. This indicates a lack of testing (this mod is public for around a year) and therefore lead to my doubt of "half complete hackathon project" because many of such hackathon project (including mine) only works on several conditions and fails (violently or not) if other inputs are given. 

Then, when the weird disappearing issue happens, I began to look at other parts of GuiBonfire, and immediately I got the feeling that this class needs some refactoring before it is clear and easy to maintain. But I was lacking the necessay time to do this (I always want to improve every opensource software to their bests) and we had to desperately switch to something else.

And, about that Java 8 thing. The way I'm suggesting is more idomatic and can be easily parallelized by switching from stream() to parallelStream(). It's also clearer to understand the intention of the code. It doesn't affect performance too much for now (IIRC 1%-6%) but it definitely had more overhead than a simple loop. Removing Java 8 isn't a must because, um, hey, my mods has been depending on them since 1.7.10, well before mojang enforces Java8. I'm saying that this is clearly a misuse of API. Following idomatic approach is always a good habits to have.

Anyhow, enjoy your college life. It's a new start.

**Comment by Glease** [comment]
Well I must say sorry in advance, yesterday we were in a rush from beta to public but this bonfire crashing and then disappearing really annoyed us so I may have been a bit too rude.

So first off, I will skip the disappearing issue. I'm not on my develop machine and can't show you how this bug is occuring. I'll just talk about something I've found within GuiBonfire. First it is crashing whenever there are 7n-1 bonfires in a dimension. This indicates a lack of testing (this mod is public for around a year) and therefore lead to my doubt of "half complete hackathon project" because many of such hackathon project (including mine) only works on several conditions and fails (violently or not) if other inputs are given.

Then, when the weird disappearing issue happens, I began to look at other parts of GuiBonfire, and immediately I got the feeling that this class needs some refactoring before it is clear and easy to maintain. But I was lacking the necessay time to do this (I always want to improve every opensource software to their bests) and we had to desperately switch to something else.

And, about that Java 8 thing. The way I'm suggesting is more idomatic and can be easily parallelized by switching from stream() to parallelStream(). It's also clearer to understand the intention of the code. It does affect performance a bit (IIRC 1%-6%) but it definitely had more overhead than a simple loop. Removing Java 8 isn't a must because, um, hey, my mods has been depending on them since 1.7.10, well before mojang enforces Java8. I'm saying that this is clearly a misuse of API. However following idomatic approach is always a good habits to have. Clear code may not yet be obvious to you, but as you code more or you begin to revisit your old projects, you will immediately get my point.

Anyhow, enjoy your college life. It's a new start.


PS: Sorry I forgot to log out the robot account of our organization, just switched back to the normal account.

--- Original Message ---

**Comment by Wehavecookies56** [comment]
Which version of Bonfires are you using? Because the indexing I think I fixed in one of the more recent versions. I guess you're on 1.10.2 which I should probably fix as it seems a lot of people are still using it, I'm just really bad at supporting multiple versions.
I think I possibly have found a fix to the disappearing although it's hard to test when I can't seem to cause it to happen.
Also streams do seem pretty handy so I've converted every foreach to a stream. So thanks for making me aware of them.

And thanks, so far it's been pretty good :)

**Comment by plunginghornets** [comment]
Any plans for fixing the actual crashing issue in 1.12? I have the same issue as the original post here. I finally started building my modpack that is basically centered around this mod. I made a lot of progress before I bothered trying to test a bonfire, and it crashes every time.

**Comment by Wehavecookies56** [comment]
Sorry I haven't had too much time to work on the mod but I believe I've fixed this issue and I've fixed some other bugs as well so I should be getting a new release ready soon
